[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/Audio/*.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
    Cache-Control = "public, max-age=31536000"
